name: VER Production Services
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4193548
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PS Showcase
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#50376C'
    - '#331D3A'
  brandStrength: 0.9426523
  lightness: 0.04480287
  saturation: 0.7706093
  rhythmicContrast: 0.6935484
purpose: []
