favicon: null
name: VER Production Services
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7706093
  brandStrength: 0.9426523
  lightness: 0.04480287
  brandColors:
    - '#000000'
    - '#50376C'
    - '#331D3A'
  rhythmicContrast: 0.6935484
typography_spectrum: 0.4193548
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
